apiVersion: v1
kind: Service
metadata:
  name: opencost
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: opencost
# kubectl apply -f Service.yaml
